name: for_single_platform

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        sudo apt install -y libgtest-dev
        cmake -H. -B_build
        cmake --build build

    - name: Tests
      run: |
        build/main
        
